import { LockKeyhole, Mail, UserRound } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { AuthBrand } from '../../components/auth/AuthBrand'
import { AuthInput } from '../../components/auth/AuthInput'
import { useAuth } from '../../hooks/useAuth'

export function SignupPage() {
  const { signUp } = useAuth(); const navigate = useNavigate()
  const [form, setForm] = useState({ email: '', password: '', passwordConfirm: '', nickname: '' }); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [submitting, setSubmitting] = useState(false)
  const update = (field: keyof typeof form) => (event: React.ChangeEvent<HTMLInputElement>) => setForm((value) => ({ ...value, [field]: event.target.value }))
  const submit = async (event: FormEvent) => { event.preventDefault(); if (form.password !== form.passwordConfirm) { setError('비밀번호가 일치하지 않습니다.'); return } setError(''); setNotice(''); setSubmitting(true); try { const result = await signUp({ email: form.email, password: form.password, nickname: form.nickname }); if (result.requiresEmailConfirmation) setNotice('인증 메일을 보냈습니다. 이메일 인증 후 로그인해주세요.'); else navigate('/setup/team', { replace: true }) } catch (caught) { setError(caught instanceof Error ? caught.message : '회원가입에 실패했습니다.') } finally { setSubmitting(false) } }
  return <div className="w-full max-w-md"><AuthBrand /><section className="rounded-[28px] border border-slate-200/80 bg-white p-6 shadow-xl shadow-slate-200/60 sm:p-8"><div className="mb-7"><h2 className="text-xl font-black">새로운 시즌을 시작해요</h2><p className="mt-1 text-sm text-slate-500">가입 후 나의 응원팀을 선택할 수 있어요.</p></div><form onSubmit={submit} className="space-y-4"><AuthInput label="이메일" icon={Mail} type="email" value={form.email} onChange={update('email')} placeholder="name@example.com" autoComplete="email" required /><AuthInput label="닉네임" icon={UserRound} value={form.nickname} onChange={update('nickname')} placeholder="Ballog에서 사용할 이름" maxLength={20} required /><AuthInput label="비밀번호" icon={LockKeyhole} type="password" value={form.password} onChange={update('password')} placeholder="8자 이상 입력하세요" minLength={8} autoComplete="new-password" required /><AuthInput label="비밀번호 확인" icon={LockKeyhole} type="password" value={form.passwordConfirm} onChange={update('passwordConfirm')} placeholder="한 번 더 입력하세요" minLength={8} autoComplete="new-password" required />{error && <p role="alert" className="rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-600">{error}</p>}{notice && <p role="status" className="rounded-xl bg-blue-50 px-4 py-3 text-sm font-semibold text-blue-700">{notice}</p>}<button disabled={submitting || Boolean(notice)} className="min-h-13 w-full rounded-2xl bg-slate-950 font-bold text-white shadow-lg transition hover:bg-slate-800 disabled:opacity-60">{submitting ? '가입 중...' : '회원가입'}</button></form><p className="mt-6 text-center text-sm text-slate-500">이미 계정이 있나요? <Link to="/login" className="font-bold text-slate-950 underline underline-offset-4">로그인</Link></p></section></div>
}
