import { Check, ChevronRight } from 'lucide-react'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { teamThemes } from '../../data/teamThemes'
import { useTheme } from '../../hooks/useTheme'
import { useAuth } from '../../hooks/useAuth'
import type { TeamId } from '../../types/team'
import { TeamLogo } from '../../components/common/TeamLogo'

export function TeamSetupPage() {
  const { completeTeamSetup } = useAuth(); const { favoriteTeam, setFavoriteTeam, theme } = useTheme(); const [selected, setSelected] = useState<TeamId>(favoriteTeam); const navigate = useNavigate()
  const selectTeam = (teamId: TeamId) => { setSelected(teamId); setFavoriteTeam(teamId) }
  const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const completeSetup = async () => { setSaving(true); setError(''); try { await completeTeamSetup(selected); navigate('/', { replace: true }) } catch (caught) { setError(caught instanceof Error ? caught.message : '응원팀 저장에 실패했습니다.'); setSaving(false) } }
  return <div className="w-full max-w-3xl py-4"><header className="mb-7 text-center"><span className="inline-flex rounded-full bg-team-soft px-3 py-1 text-xs font-black text-team">마지막 단계</span><h1 className="mt-4 text-3xl font-black tracking-tight">어느 팀을 응원하세요?</h1><p className="mt-2 text-sm text-slate-500">선택한 팀의 컬러로 나만의 Ballog가 완성됩니다.</p></header><section className="rounded-[30px] border border-slate-200/80 bg-white p-5 shadow-xl shadow-slate-200/50 sm:p-8"><div className="mb-6 overflow-hidden rounded-2xl bg-gradient-team p-5 text-white transition-colors"><p className="text-xs font-bold text-white/60">THEME PREVIEW</p><div className="mt-2 flex items-end justify-between"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-xl bg-white/90 p-1"><TeamLogo teamId={selected} className="h-full w-full" /></span><div><h2 className="text-xl font-black">{theme.teamName}</h2><p className="mt-1 text-xs text-white/65">2026 시즌을 함께 기록해요</p></div></div><div className="flex gap-2"><i className="h-8 w-8 rounded-lg border border-white/20" style={{ backgroundColor: theme.secondaryColor }} /><i className="h-8 w-8 rounded-lg border border-white/20" style={{ backgroundColor: theme.accentColor }} /></div></div></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{teamThemes.map((team) => { const active = selected === team.id; return <button key={team.id} onClick={() => selectTeam(team.id)} className={`relative flex flex-col items-center gap-2 rounded-2xl border p-3 transition hover:-translate-y-0.5 ${active ? 'border-team bg-team-soft ring-2 ring-team' : 'border-slate-200 hover:border-slate-300'}`}><TeamLogo teamId={team.id} className="h-11 w-11" /><span className="text-sm font-bold">{team.shortName}</span>{active && <span className="absolute right-2 top-2 grid h-5 w-5 place-items-center rounded-full bg-team text-white"><Check className="h-3 w-3" /></span>}</button> })}</div>{error && <p className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-600">{error}</p>}<button disabled={saving} onClick={completeSetup} className="mt-7 flex min-h-13 w-full items-center justify-center gap-2 rounded-2xl bg-team font-bold text-white shadow-lg shadow-team transition hover:brightness-110 disabled:opacity-60">{saving ? '저장 중...' : '이 팀으로 시작하기'} <ChevronRight className="h-4 w-4" /></button></section></div>
}
